name: uridachi
description: "A new Flutter project."
publish_to: 'none'
version: 1.0.0+1

environment:
  sdk: '>=3.2.6 <4.0.0'

dependencies:
  flutter_localizations:
    sdk: flutter
  cupertino_icons: ^1.0.2
  firebase_core: ^3.2.0
  firebase_auth: ^5.1.2
  cloud_firestore: ^5.1.0
  email_auth: ^2.0.0
  image_picker: ^1.1.2
  foundation: ^0.0.5
  firebase_storage: ^12.1.1
  uuid: ^4.3.3
  intl: ^0.19.0
  clay_containers: ^0.3.4
  flutter_rating_bar: ^4.0.1
  googleapis: ^13.0.0
  googleapis_auth: ^1.6.0
  readmore: ^3.0.0
  translator: ^1.0.0
  get: ^4.6.6
  provider: ^6.1.1
  logging: ^1.2.0
  mailer: ^6.1.0
  firebase_messaging: ^15.0.3
  timeago_flutter: ^3.6.0
  instant: ^0.5.1
  firebase_app_check: ^0.3.0+3
  country_flags: ^3.0.0
  google_api_availability: ^5.0.0
  cr_mentions: ^0.0.1+1
  flutter_staggered_grid_view: ^0.7.0
  rive: ^0.13.14

dependency_overrides:
  web: ^0.5.1

dev_dependencies:
  flutter_launcher_icons: ^0.13.1
  flutter_test:
    sdk: flutter
  flutter_lints: ^5.0.0


flutter_launcher_icons:
  android: true
  ios: true
  image_path: "assets/images/app_logo.png" 

flutter:
  uses-material-design: true
  generate: true

  assets:
    - assets/images/
    - lib/l10n/
